name: Slate CI

on:
  push:
    branches: [ master ]
    tags:
      - "v*"
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install_deps
      run: sudo apt install nasm clang
    - name: build
      run: sudo make all

#  codeql:
#    
#    runs-on: ubuntu-latest
#    
#    steps:
#    - name: checkout
#      uses: actions/checkout@v2
#      with:
#        fetch-depth: 2
#
#    - run: git checkout HEAD^2
#      if: ${{ github.event_name == 'pull_request' }}
#
#    - name: codeql_init
#      uses: github/codeql-action/init@v1
#      with:
#        languages: cpp
#    - name: codeql_autobuild
#      uses: github/codeql-action/autobuild@v1
#
#    - name: codeql_analyze
#      uses: github/codeql-action/analyze@v1